// config.js
const fs = require("fs");
require("dotenv").config();

const config = {
  SESSION_ID: process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUUtKZWJnTXNNU295L09CQ1lJTzJaay9lVUJPbHJIOTBQNWtDWlNiZzdXbz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUUlBbHdBbE14d0MwK3hHWXBjakUwZDFTNXQwT1dGbTBWMjVvZHJ3cE5IZz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJnTkVFR1pleGI1SEUxRlRvTUxGUEdjQkEzSTFCWVY4RW5WRW1vRTR0UzEwPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ1OHEyT1IyS1l3QlZPNHhSWWNzS1AzemovY0FSeUZaL2dWTDJpeGxjSGs0PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InNBSVNpNmVMeDBwTk1WcW9XR0d5cU9Ua2dyblVmWnpsdE5KZFJKVEg2a2s9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik5aOVJZc3o1QjBBMzR1THV5Ry9JaWNuZFdVSzcrbXYydFpYSWhsaE9JVjg9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiK0dZMmZUTU9mTk8zNkhVM0tWcXJ1OFJZZUNVaUhmRTZnRFViUUNBaGRVaz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoici8zYkY2WmtUUWJLUVZRaFhjMlF6SWw3RmZ2aC9jQkpUSFA3VkZNck9YRT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik1BQXZKQURzOTRFdDNCU3dOMHpiRitCOVNSTWpJWG4yVkgvWWFnUzlmY0FnUzFZUEhvdk1KZDl3N0RWTTAwVDNCNytPRDJHd3NFVW1DcnFDUDcxVEJBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6NjgsImFkdlNlY3JldEtleSI6IjlXQXVsckdWMnB0Rk1EZ29GQy80eXowb2pBOWtRT2l4NTdLNzJ5U3F1aEU9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbXSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjAsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJkZXZpY2VJZCI6ImRCVGsyampQVDlTc29qVEp1VjRJR0EiLCJwaG9uZUlkIjoiOWVmY2RiY2UtYzcwZS00ODliLWJlMGQtZDA4NTYzNDBkNGM4IiwiaWRlbnRpdHlJZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkZSdTI3Z1JreXFQU25xNmdCZ3lRZG4wOHVHcz0ifSwicmVnaXN0ZXJlZCI6dHJ1ZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJGQVZRdFdWeHhpQ1o4Z0dQSnBQZXBsN2JyOHM9In0sInJlZ2lzdHJhdGlvbiI6e30sInBhaXJpbmdDb2RlIjoiRVRORUhUSE4iLCJtZSI6eyJpZCI6IjUwOTQxNTQ3NzIzOjM1QHMud2hhdHNhcHAubmV0IiwibmFtZSI6IkJPVUxFJ0wifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ0xLYzUrMERFTlQ0emJzR0dBSWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6IlRrZk5BdllVN1laLzFtaS8rRTBlU0hacmM3dTF5Vks3SkVZTlBNZU1GZ2M9IiwiYWNjb3VudFNpZ25hdHVyZSI6IjVudEdzUllyL0dvNklNdFM0c3Rma3VLeVdOY1pIbFV5c01TeWc4TEtPbVU3NmJWSElhdnhDS3NGQTE5N2hOeGFJRmk5NTY0OHBZU0p0V2ROcXN3WER3PT0iLCJkZXZpY2VTaWduYXR1cmUiOiI2NVJLRjIyY2Z0MER2U2s3d084TGxqWnpkT2lKUTZGU2YzVlc5WitFMUU0Wmc0cFlRMXZQUzJ5d2Zkb3hkazhhTnpYRHhhYlg0L3l3SUpySEVQb3lDQT09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjUwOTQxNTQ3NzIzOjM1QHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlU1SHpRTDJGTzJHZjlab3YvaE5Ia2gyYTNPN3RjbFN1eVJHRFR6SGpCWUgifX1dLCJwbGF0Zm9ybSI6InNtYmEiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MzU2MjE3Mjl9",
  PREFIX: process.env.PREFIX || '.',
  AUTO_STATUS_SEEN: process.env.AUTO_STATUS_SEEN !== undefined ? process.env.AUTO_STATUS_SEEN === 'true' : true, 
  AUTO_DL: process.env.AUTO_DL !== undefined ? process.env.AUTO_DL === 'true' : false,
  AUTO_READ: process.env.AUTO_READ !== undefined ? process.env.AUTO_READ === 'true' : false,
  AUTO_TYPING: process.env.AUTO_TYPING !== undefined ? process.env.AUTO_TYPING === 'true' : false,
  AUTO_RECORDING: process.env.AUTO_RECORDING !== undefined ? process.env.AUTO_RECORDING === 'true' : false,
  ALWAYS_ONLINE: process.env.ALWAYS_ONLINE !== undefined ? process.env.ALWAYS_ONLINE === 'true' : true,
  AUTO_REACT: process.env.AUTO_REACT !== undefined ? process.env.AUTO_REACT === 'true' : false,
   /*auto block only for 212 */
  AUTO_BLOCK: process.env.AUTO_BLOCK !== undefined ? process.env.AUTO_BLOCK === 'true' : true,
  
  
  REJECT_CALL: process.env.REJECT_CALL !== undefined ? process.env.REJECT_CALL === 'true' : false, 
  NOT_ALLOW: process.env.NOT_ALLOW !== undefined ? process.env.NOT_ALLOW === 'true' : true,
  MODE: process.env.MODE || "public",
  OWNER_NAME: process.env.OWNER_NAME || "☞⌜ KG TECH⌝☜",
  OWNER_NUMBER: process.env.OWNER_NUMBER || "237659535227",
  GEMINI_KEY: process.env.GEMINI_KEY || "AIzaSyCUPaxfIdZawsKZKqCqJcC-GWiQPCXKTDc",
  WELCOME: process.env.WELCOME !== undefined ? process.env.WELCOME === 'true' : false, 
};


module.exports = config;
